In [1]:
import numpy as np

### 1.Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.

In [4]:
n=np.array(['priya','latur ','  k'])
t=np.char.strip(n)
print(t)

['priya' 'latur' 'k']


In [7]:
import pandas as pd

### 2.Write a NumPy program to find the most frequent value in an array.

In [10]:
s=np.array([1,2,3,3,3,4])
k=pd.Series(s).mode()[0]
print(k)

3


In [28]:
def find(arr):
    count = {}
    for i in arr:
        if i in count:
            count[i] += 1
        else:
            count[i] = 1

    max_count = 0
arr=([1,2,3,3,4])
s=find(arr)
print(s)

None


### 3.Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates

In [30]:
matrix = np.random.randint(5, size=(5, 2))

print(matrix)

x, y = matrix[:, 0],matrix[:, 1]
r = np.sqrt(x**2 + y**2)
print(r)

[[1 4]
 [2 0]
 [2 1]
 [4 1]
 [0 0]]
[4.12310563 2.         2.23606798 4.12310563 0.        ]


### 4.Write a NumPy program to check two random arrays are equal or not.

In [16]:
n=np.array([1,2,3,4])
t=np.array([1,2,3,4,5])
if len(n)==len(t):
    print('equal')
else:
    print('no')

no


In [19]:
s=np.random.rand(10,2)
z=np.random.rand(10,2)
if len(s)==len(z):
    print('equal')
else:
    print('no')

equal


In [22]:
s=np.random.rand(10,2)
z=np.random.rand(10,2)
if np.array_equal(s,z):
    print('equal')
else:
    print('not equal')

no


### 5. Write a NumPy program to normalize a 3x3 random matrix

In [23]:
matrix = np.random.random((3, 3))
print(matrix)


n = np.linalg.norm(matrix)


m = matrix / n
print(m)

[[0.89339158 0.08654444 0.64306433]
 [0.65045516 0.99673201 0.47072006]
 [0.32709808 0.30702563 0.39979912]]
[[0.49799052 0.04824123 0.35845418]
 [0.36257394 0.5555941  0.26238677]
 [0.18232961 0.17114092 0.22285432]]


In [ ]:
### 6.