### 1.Write a Python script to concatenate following dictionaries to create a new one.

In [5]:
a={'hi':'hello','name':'priya','is':'tia'}
b={'num':'seri','py':'pyhton'}
c={}
c.update(a)
c.update(b)
print(c)


{'hi': 'hello', 'name': 'priya', 'is': 'tia', 'num': 'seri', 'py': 'pyhton'}


### 2.Write a Python script to check whether a given key already exists in a dictionary.

In [10]:
dict1={2:3,3:4,5:6}
def exist(a):
    if a in dict1:
        print('yes')
    else:
        print('no')

In [11]:
exist(2)

yes


### 3.Write a Python program to sum all the items in a dictionary.

In [7]:
dict1={20:12,2:3,4:6}
b=sum(dict1.keys())
c=sum(dict1.values())
t=b+c
t

47

### 4 Write a NumPy program to get the powers of an array values element

In [14]:
import numpy as np

In [20]:
n=np.array([1,2,3])
c=n**2
c

array([1, 4, 9])

### 5.Write a NumPy program to get the element-wise remainder of an array of division.

In [22]:
p=np.array([2,16,20,15])
t=p%10
print(t)

[2 6 0 5]


In [27]:
k=np.array([2,16,20,15])
o=np.array([10])
s=np.remainder(k,o)
print(s)

[2 6 0 5]


In [28]:
k=np.array([14,16,20])
o=np.array([2,3,5])
s=np.remainder(k,o)
print(s)

[0 1 0]


### 6.Write a NumPy program to insert a space between characters of all the elements of a given array.

In [32]:
t=np.array(['priya','latur'],dtype=np.str)
n=np.char.join(" ",t)
print(n)

C:\Users\CITS\AppData\Local\Temp\ipykernel_1612\790138326.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  t=np.array(['priya','latur'],dtype=np.str)


['p r i y a' 'l a t u r']


### 7.Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array

In [43]:
m=np.array([ 'book'  ,'pen' ,'try'  ])
n=np.char.strip(m)
print(n)

['book' 'pen' 'try']
