In [1]:
import numpy as np

### 1.Write a NumPy program to compute cross-correlation of two given arrays

In [5]:
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
n=np.correlate(a,b)
print(n)

[80]


In [6]:
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
n=np.correlate(a,b,mode='full')
print(n)

[ 9 26 50 80 65 46 24]


### 2.Write a NumPy program to compute Pearson product-moment correlation coefficients of two given arrays

In [9]:
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
n=np.corrcoef(a,b)
print(n)

[[1. 1.]
 [1. 1.]]


In [10]:
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
n=np.corrcoef(a,b)[0][1]
print(n)

1.0


### 3.Write a NumPy program to compute the median of flattened given array.

In [13]:
n=np.array([[1,2,3],[4,5,6]])
new=n.flatten()
print(new)

[1 2 3 4 5 6]


In [14]:
t=np.median(new)
print(t)

3.5


### 4.Write a NumPy program to compute the weighted of a given array.

In [19]:
n=np.array([1,2,3,4])
w=np.array([0.5,0.2,0.4,0.7])
new=np.average(n,weights=w)
print(new)


2.7222222222222223


### 5. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis

In [21]:
n=np.array([2,3,6,7])
t=n.max()
t

7

In [23]:
m=n.min()
m

2

In [24]:
f=t-m
f

5

In [30]:
# 2d array
d=np.array([[2,3,4,5],[10,6,7,8]])
x=np.max(d,axis=1)-np.min(d,axis=1)
x

array([3, 4])

### 7.Write a NumPy program to get the indices of the sorted elements of a given array.

In [32]:
n=np.array([2,3,5,6,7])
t=np.argsort(n)
t

array([0, 1, 2, 3, 4], dtype=int64)

### 8.Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

In [ ]:
# complex num=3j,2j
arr = np.array([2+3j, 4-1j, 3+4j, 2-1j])

### 9.Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data

In [ ]:
id=np.array([1,2,3,4])
height=np.array([145,160,154,135])
